version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    image: docker_postgres_node_express_ts
    build: .
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules/
            - .git
            - .gitignore
        - action: rebuild
          path: ./package.json
    ports:
      - 1337:1337
