
###
POST http://localhost:1337/api/person
Content-Type: application/json

{"name": "Kez Anr", "job": "Softwar Developer"}
###

###
GET http://localhost:1337/api/person
Content-Type: application/json

###

