
### Register a new User
POST http://localhost:1337/api/auth/register
Content-Type: application/json

{"first_name": "James","last_name": "Bond", "email": "007@gmail.com", "password": "Password123!"}
###

### Confirm email through OTP
POST http://localhost:1337/api/auth/otp/526595
Content-Type: application/json
x-auth-token: {{token}}
###

### Login with Email and Password
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{"email": "007@gmail.com", "password": "Password123!"}
###

### Initialize with JWT
POST http://localhost:1337/api/auth/initialize
Content-Type: application/json
x-auth-token: {{token}}

###