### Get a User by uuid
GET http://localhost:1337/api/user/manage/72746fa2-e032-4fdb-953e-fc7f2230d322
Content-Type: application/json

###

### Delete a User by uuid
DELETE http://localhost:1337/api/user/manage/08874ab8-b645-41c0-806f-2b575136f77c
Content-Type: application/json

###

### Get all Users
GET http://localhost:1337/api/user/list
Content-Type: application/json

###

